// Generated by CoffeeScript 1.8.0

/* ROUTING */

(function() {
  Router.configure({
    notFoundTemplate: 'fourZeroFour'
  });

  Router.map(function() {
    this.route('indexRoute', {
      path: '/',
      controller: 'IndexController'
    });
    this.route('playersRoute', {
      path: '/players',
      controller: 'PlayersController'
    });
    this.route('matchRoute', {
      path: '/match/:_id',
      controller: 'MatchController'
    });
    this.route('matchListRoute', {
      path: '/match',
      controller: 'MatchListController'
    });
    this.route('profileRoute', {
      path: '/u/:username',
      controller: 'ProfileController'
    });
    return this.route('leaderRoute', {
      path: '/leaderboard',
      controller: 'LeaderController'
    });
  });

  IronRouterProgress.configure({
    spinner: false
  });

  console.log("Configured router, " + Router.routes.length + " routes defined");

}).call(this);

//# sourceMappingURL=router.js.map
