// Generated by CoffeeScript 1.8.0
(function() {
  this.Players = new Mongo.Collection('players');


  /* CLIENT AUTHORZATIONS */

  Players.allow({
    insert: function(userId, doc) {
      return true;
    }
  });

}).call(this);

//# sourceMappingURL=users.js.map
